name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> .env.production
          echo "NEXT_PUBLIC_GCP_API_KEY=${{ secrets.GCP_API_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_GCP_STORAGE_BUCKET=${{ secrets.GCP_STORAGE_BUCKET }}" >> .env.production
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.production
        
      - name: Build project
        run: npm run build
        
      - name: Export static files
        run: npm run export
        
      - name: Add .nojekyll file
        run: touch out/.nojekyll
        
      - name: Add CNAME file
        run: echo "${{ secrets.CNAME_DOMAIN }}" > out/CNAME
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out 
 